#!/usr/bin/env bash
# Generate Tier-2 catalogs from upstream. For each sources.yml entry whose
# `enumerate:` is not '-', list its skill subdirectories, fetch each SKILL.md, and
# write references/skill-bank/catalog/<key>.md (header + table). The table body is
# produced by scripts/format_catalog.sh (unit-tested); this script is the network
# adapter (uses gh + curl) and is not unit-tested. An enumerate of '.' means the repo
# root. Run: bash scripts/build_skill_bank_catalog.sh
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
SOURCES="$ROOT/references/skill-bank/sources.yml"
OUTDIR="$ROOT/references/skill-bank/catalog"
FORMAT="$HERE/format_catalog.sh"
TODAY="$(date +%F)"

command -v gh >/dev/null 2>&1 || { echo "build: gh CLI required" >&2; exit 2; }
mkdir -p "$OUTDIR"

unquote() { local s="$1"; s="${s%\"}"; s="${s#\"}"; printf '%s' "$s"; }

awk '
  /^- key:/                 { if (key!="") print key"|"repo"|"enum; key=$3; repo=""; enum="-" }
  /^[[:space:]]+repo:/      { repo=$2 }
  /^[[:space:]]+enumerate:/ { enum=$2 }
  END { if (key!="") print key"|"repo"|"enum }
' "$SOURCES" | while IFS='|' read -r key repo enum; do
  key="$(unquote "$key")"; repo="$(unquote "$repo")"; enum="$(unquote "$enum")"
  [ "$enum" = "-" ] && { echo "skip $key (enumerate: -)"; continue; }
  ownerrepo="${repo#https://github.com/}"; ownerrepo="${ownerrepo%/}"
  if [ "$enum" = "." ]; then apipath="contents"; rawprefix=""; else apipath="contents/$enum"; rawprefix="$enum/"; fi
  echo "building $key from $ownerrepo (enumerate: $enum) ..."
  tmplist="$(mktemp)"
  if ! gh api "repos/$ownerrepo/$apipath?ref=main" \
        --jq '.[] | select(.type=="dir") | .name' > "$tmplist" 2>/dev/null; then
    echo "  WARN: could not list $ownerrepo/$enum — skipping $key" >&2
    rm -f "$tmplist"; continue
  fi
  infile="$(mktemp)"
  while IFS= read -r slug; do
    [ -z "$slug" ] && continue
    sk="$(mktemp)"
    if curl -fsSL "https://raw.githubusercontent.com/$ownerrepo/main/${rawprefix}${slug}/SKILL.md" -o "$sk" 2>/dev/null; then
      printf '%s:%s\t%s\n' "$key" "$slug" "$sk" >> "$infile"
    else
      rm -f "$sk"
    fi
  done < "$tmplist"
  if [ ! -s "$infile" ]; then
    echo "  WARN: no SKILL.md found under $ownerrepo ($enum) — skipping $key" >&2
    rm -f "$infile" "$tmplist"; continue
  fi
  {
    echo "# $key — full catalog (auto-generated by scripts/build_skill_bank_catalog.sh; do not hand-edit)"
    echo "# source: $repo · synced: $ownerrepo@main $TODAY"
    echo
    bash "$FORMAT" < "$infile"
  } > "$OUTDIR/$key.md"
  echo "  wrote catalog/$key.md"
  cut -f2 "$infile" | xargs -r rm -f
  rm -f "$infile" "$tmplist"
done
echo "done."
